# Generated by Django 3.1.3 on 2020-11-09 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_remove_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administratoruser',
            options={'verbose_name': 'Administrator User'},
        ),
        migrations.AlterModelOptions(
            name='normaluser',
            options={'verbose_name': 'Normal User'},
        ),
        migrations.CreateModel(
            name='PromoUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_points', models.DecimalField(decimal_places=1, max_digits=10)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promos_use', to='promo.promo')),
            ],
        ),
    ]
